version: '3'

services:
    supermonk-opentsdb:
        container_name: supermonk-opentsdb
        image: petergrace/opentsdb-docker:latest
        ports:
            - 4242:4242
            - 60030:60030
        volumes:
             - hbase_data:/data/hbase
             - tsdb_tmp:/tmp

    supermonk-grafana:
        container_name: supermonk-grafana
        image: grafana/grafana:latest
        ports:
            - 3000:3000
        links:
            - supermonk-opentsdb
        volumes:
            - grafana_etc:/etc/grafana
            - grafana_lib:/var/lib/grafana
            - grafana_plugins:/var/lib/grafana/plugins
            - grafana_log:/var/log/grafana

#    add_grafana_datasource:
#        build:
#            context: .
#            dockerfile: Dockerfile.add_grafana_datasource
#        environment:
#Reference
#            GRAFANA_HOST: grafana
#            TSDB_HOST: opentsdb
#        links:
#            - grafana

    supermonk-elk:
        image: sebp/elk
        container_name: supermonk-elk
        ports:
          - "5601:5601"
          - "9200:9200"
          - "5044:5044"
        networks:
          - elk-net


volumes:
    grafana_etc:
    grafana_lib:
    grafana_plugins:
    grafana_log:
    hbase_data:
    tsdb_tmp:

networks:
    elk-net:

