version: '3'

services:
    supermonk-webapp:
        container_name: supermonk-springboot-app
        image: supermonk-springboot-app:latest
        ports:
            - 8301:8301
        volumes:
             - /tmp/webapp/var:/var/log